### ISSUE TITLE
Build issues on macOS

### ISSUE THREAD

**Issue by rod-chapman** [pablotron/fips203ipd#1]
Two issues with building on macOS (v13.6.6 with Apple Silicon M1 Pro, using Apple's clang 15.0.0)

1. Apple's sys/random.h does not declare "getrandom()" but instead declares "getentropy()" that
has only 2 parameters and returns an "int" with 0 indicating success and -1 indicating failure, so
I needed to change rand_bytes.h to have something like:

```
  const int got = getentropy(buf, len);
  if (got == -1) {
    // print error message, exit with error
    errx(-1, "getrandom() failed");
  }
```

2. Apple's clang does not support --sanitize=leak, so I had to remove that one...

**Comment by rod-chapman** [comment]
I have tried this with gcc 13.1.0 with the same results. With that change to rand_bytes.h and Makefile, compilation is fine and all tests pass with both clang and gcc.

**Comment by pablotron** [comment]
Hi @rod-chapman,

Thanks for the fix.  I changed `rand_bytes()` to use `getentropy()` and removed `-fsanitize=leak` from the `Makefile`.  These fixes will go out with the next release tag.
